apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-operator-catalog 
  namespace: openshift-marketplace 
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: legacy
  image: host2.ocp-poc-demo.com:8443/<namespace>/redhat-operator-index:v4.18 
  displayName: My Operator Catalog
  publisher: <publisher_name> 
  updateStrategy:
    registryPoll: 
      interval: 30m
