kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
 platform:
   channels:
   - name: stable-4.18
     type: ocp
   graph: true
 operators:
 - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
   packages:
   - name: advanced-cluster-management
   - name: multicluster-engine
 additionalImages:
 - name: registry.redhat.io/ubi8/ubi:latest
 - name: quay.io/openshifttest/hello-openshift@sha256:4200f438cf2e9446f6bcff9d67ceea1f69ed07a2f83363b7fb52529f7ddd8a83
