kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
 operators:
 - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
   packages:
   - name: advanced-cluster-management
   - name: multicluster-engine
   - name: ocs-client-operator
   - name: ocs-operator
   - name: odf-csi-addons-operator
   - name: odf-dependencies
   - name: odf-operator
   - name: kubevirt-hyperconverged
   - name: local-storage-operator
 additionalImages:
 - name: registry.redhat.io/ubi8/ubi:latest
 - name: quay.io/openshifttest/hello-openshift@sha256:4200f438cf2e9446f6bcff9d67ceea1f69ed07a2f83363b7fb52529f7ddd8a83
